{% set name = "lockfile" %}
{% set version = "0.12.2" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pbr >=1.8

  run:
    - python

test:
  imports:
    - lockfile

about:
  home: https://launchpad.net/pylockfile
  license: MIT
  # license_file: No MANIFEST.in - see https://bugs.launchpad.net/pylockfile/+bug/1622259
  license_family: MIT
  summary: 'Platform-independent file locking module'
  doc_url: http://docs.openstack.org/developer/pylockfile/
  dev_url: http://git.openstack.org/cgit/openstack/pylockfile

extra:
  recipe-maintainers:
    - pmlandwehr
