travis:
  secure:
    BINSTAR_TOKEN: UoxSMgfi/a0kSQIDhMLd4ttexqmlAqEEZbfxHh/Cg2nu4IVfm8QXDcFDcVdva4Q2lKYtgQm+XpLnlhMEE4yb13viF3O9IOsptu1RKgqRsaptypOrnfMU0A30f3aKWFWH2MeG/wOohbxaOAM3MqYQsz7+RxYlim4SwFDeDHeDynAOjjnIL2cHcqoU8jaVnx3RBDQOGL/F7gwLog/cTNg5J/gdI3RoJ6ynJpvGA/voMVc6GIvMox61DRttNyj3LhHaiBS/ehrcr0/1OyCTRS1toi3hL2XPSMOhb+6PKoR9TcupLEManEjSWkaEDouiWNInDQxpadiPWbt+Pl2gOnowfAgq1Xdu1QpzCeSVX19fPucPIen0d09EAGxt4DnR2IFYUblXBHR7X8L0LxaPdphWpk8VfOTpz6Q6Sn1ojUrH2zmY+N3QVMmU93/QrXayFC1p9o2Z0gwa/wu+U3us+o1OIw6G2eFRRfz9/sTSPRvknkNg/cku+irdZcI0TbXjhwi2dwARa5vUkM1a6Jxfvj+waLeZnPO50RaiFnXESWGM2vwiNVs3rBQ2LWuQetPd/eLAyiUGRfIKwCtdRJHYwCTnIRZQjL8B7FVtE4b75MBBcRsK7Nhb7dd4q7zPOvvZvg4gMS/gsP57kmfHHbqRUOEiTk8+cMH7YVTH1I7e7GYj8GQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
