travis:
  secure:
    BINSTAR_TOKEN: GR8/Aay0s3t8u4dnIBsznPpFOQT2gTki+QpiV5nwZGRuIrLJKwRDvIpwZDNeqVYSE+zojRh9D4QbnHWfyQc5dYZ4x+DChceWaFM3iX10qylzn+bLwNoVQMGquZ2ZuISAYXT9XQ6Wnxn1xRSUpGPF1C9jOEVT5HnkJZLORyuKdxFwi9kvRLW3zcwwbpNx1LsNl4dSASUDaZUK/SBwiYXBgDv2wgN+iw5gYnlhIG3RP8/do42jN7q8Pt4qPlNprrjeqU9dT95ubNq5nxxVwt4VUtRgsPZjGNjw7e9CqC7JlIgl2u1XYAGyMeoYMwJgpv2jkzjyuEAj7f10oyC3YN//YCTmuQSsqPSg4Sfa+80DteZNvweL6nojudq+wA/qTezWqpp3+eeojeQI3L7mw/zlLmeBUaWVFI6Qg4sZUw6RD6zCFYauCfYpRpNIC0+ab9FDbJmNL2VMzAxC1Ua2XYJuWQcDECGIGtCpSXq8qlt9R7a21CeO//fpdcYS2fgEnzayay6rZMS9EtfDYqGaNzIyDnzBP1+HzJDMeIireYJH0B9Dn+zl0TUQS0Nie0qWJsjK5JJmHJv08Be7oSUpCbK8yd86Lq/s5UVfOdwSCHj5g64+Bn+uYuacGXcqtI97ZYt+7J9Fmk38KV76zTR251TaGjb1WJP2Z7WaOnrGuJBNwDs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
