travis:
  secure:
    BINSTAR_TOKEN: cafpK8BkY/WL4bUrdksP91QAFHXRXmhIdMq2tfndpqaiA73s+4tjs8WoIyy39xkeHm3jAdOC6CmdCsil+NNoEFxBke2M9hdg5kDGI2nLhQPtHgtjHsaIREbHRZ7nOFqVmqudMhl1juumcvQDm5yvtX0XztzqZPugv4KMlyfqFuj+iIl8odgABmwJ8dzZRM+w+8aUUQeg2WQnuF1PSp+O2kHepWxDlG83w8ydPsLXXYhviRWN95HlbX560wAGnw4hIx7eNESX500xkUeWa0U8YLq2N9I8NxAhp0VKnTSMYf92CGxiRz7OHNYZDqMXVZKu+n6/OifuZPFbfKXsirY7EmXqgYMIbzT535THg3us+GLwRc7L5Ci8Air8F/J0+UcezOyYyo8ZdRJoIrUdSXH3wihiFmmGzQkrXjJYj/GUig9lG0blMTx/v37cOtCmhV8zpVhv0WhNFVPXciBTHOxjpQlFsDqQJfdt53lVvLncMMEshUgZmq3r8CeLstHXdKvdHcQXnbHGLAe2UWEqfMZEuc0Ey+NEzJmrz1UWbtWCIzBMAbR+rJIw75MQEXfkwTr++QFWj3BdCXJiLJNFkzdfMkObwuC1GJTeKUa7JMyya5FJkd5XlviFOCJy7TfHQwgp3QYRWXlBIhzbLEng27yZIHC8Cmg+wtFTQNIDO9gQHqc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
